### ISSUE TITLE
CRAM support

### ISSUE THREAD

**Issue by ppararaj** [mskilab/fragCounter#11]
Hello,
Thanks for the software. I was able to successfully run this on a several BAM files, but I was wondering if there are plans to include support for CRAM format? 

I receive the following error when trying to run a CRAM file and looks like a modification of bamUtils will be required:

```[1] "Doing it!"
Error in bamUtils::bam.cov.tile(bam, window = as.numeric(window), chunksize = 1e+06,  :
  Cannot open BAM. A valid BAM for 'bam.file' must be provided.
Calls: fragCounter -> PrepareCov -> <Anonymous>
In addition: Warning message:
In readChar(check_gz, 4) :
  text connection used with readChar(), results may be incorrect
Execution halted
```

**Comment by ShaiberAlon** [comment]
Hi @ppararaj ,

Thank you for your interest in our tool. We don't currently have support for CRAM files and we don't have immediate plans to add this support (at least for now). What we do plan is to add an options for users to provide coverage counts from 3rd party tools and then just apply our GC and mappability correction (hoping to post updates here soon: #12 ). An (often superior) alternative to the coverage correction offered by fragCounter is using [dryclean](https://github.com/mskilab/dryclean). Dryclean works well with uncorrected read depth counts.

There are many tools that offer fast coverage depth computations, for example: [megadepth](https://bioconductor.org/packages/release/bioc/vignettes/megadepth/inst/doc/megadepth.html)

If you are using fragCounter because you wish to use [JaBbA](https://github.com/mskilab/JaBbA/), then you can use a tool of your choice for coverage depth calculation and supply that as input for JaBbA (with or without dryclean processing).

**Comment by rdmorin** [comment]
We're working with @mskilab on a meta-analysis of lymphomas. This is a show-stopper for us at the moment. Any thoughts on when this new functionality will become available?

**Comment by mskilab** [comment]
Hi Ryan- I think cram support should be pretty easy to implement.   I think can have it by Monday?

Marcin
________________________________

**Comment by rdmorin** [comment]
That would be great. Thanks Marcin!

**Comment by mskilab** [comment]
hi all - just added cram support and pushed to master --> please give it a spin and let us know!  You will need to reinstall mskilab/bamUtils as well.    Best-Marcin

**Comment by ppararaj** [comment]
Hello,
I've tested the new feature on a some GRCh37 CRAM files and it appear to work without issue. Thank you.

**Comment by mskilab** [comment]
Great
